package models

type Test struct {
	Input       string
	Output      string
	TimeElapsed float32
	MemoryUsed  int32  // TODO: specify KB/MB/Bytes
	Reason      string // Generated by checker
	Status      int8
}
