package models

type Test struct {
	Input       string  `bson:"input"`
	Output      string  `bson:"output"`
	TimeElapsed float32 `bson:"time_elapsed"`
	MemoryUsed  int32   `bson:"memory_used"` // TODO: specify KB/MB/Bytes
	Reason      string  `bson:"reason"`      // Generated by checker
	Status      int8    `bson:"status"`
}
